apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-aws
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-aws
  template:
    metadata:
      labels:
        app: demo-aws
    spec:
      containers:
        - name: demo-aws
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-port
              containerPort: {{ .Values.service.internalPort }}
          startupProbe:
            httpGet:
              path: /actuator
              port: http-port
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-port
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http-port
