spring:
  application:
    name: '@project.artifactId@'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg-demo-aws-postgresql.demo-aws.svc.cluster.local:5432/aeliseev
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc.time_zone: UTC
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml